### ISSUE TITLE
Sceneform sdk should pass through Proguard rules from Filement artifact

### ISSUE THREAD

**Issue by kenyee** [ThomasGorisse/sceneform-android-sdk#91] opened 2021-06-17 20:08 UTC
https://github.com/ThomasGorisse/sceneform-android-sdk/issues/69#issuecomment-849302503

The workaround described in this should not be needed...Filament has proguard rules for UsedBy:
https://github.com/google/filament/blob/24b88219fa6148b8004f230b377f163e6f184d65/android/proguard-rules.pro

They should be passed through and included in this sdk's proguard rules.

**Comment by romainguy** [comment] 2021-06-17 20:19
I can confirm that these ProGuard rules need to be preserved in Sceneform. We keep them up to date so it's best to rely on us doing the right thing here.

**Comment by romainguy** [comment] 2021-06-17 20:51
I'm making a change so that Filament will properly include the ProGuard rules file in its AARs. You may need to add your own `consumerProguardFiles` directive in `build.gradle` to preserve our rules though.

**Comment by ThomasGorisse** [comment] 2021-06-17 21:08
Also related : [google-ar/arcore-android-sdk/issues/1232](https://github.com/google-ar/arcore-android-sdk/issues/1232)

@kenyee Can you make a Pull Request with the current rules?
I will keep the PR branch alive so that we can keep in mind that there will have modifications on this Filament part.

**Comment by kenyee** [comment] 2021-06-17 22:31
@ThomasGorisse :
You mean add a temp one w/ a proguard file for Filament until Filament adds proguard rules properly?  Or do you mean fix how this repo handles it's rules?

**Comment by romainguy** [comment] 2021-06-17 22:40
I just made the change on our end, the next release of Filament (next week) should have it.

**Comment by ThomasGorisse** [comment] 2021-06-18 06:05
Do we need to do something to forward your rules ?

It's been a while since I worked with proguard but from what I remember we should put the view and fragment class cause they aren't marked as used from the layout res file?

I will double check but the goal for the next release will be to remove all the still living sfb classes and so (I hope) all the actual jni part from Sceneform so there might not need to be put in the proguard rules.

**Comment by kenyee** [comment] 2021-06-18 11:27
IIRC, as long as you include filament w/ "api" in your gradle file, the proguard file should be passed through.
Question is whether you have anything in this sceneform sdk that needs proguard exclusions too...then we'd need to add "consumerProguardFile" against this SDK's proguard rules file.

**Comment by kenyee** [comment] 2021-06-18 12:07
Couldn't find a proguard file in the sceneform SDK...should there be one?
Filament seems to be pulled in via an "api" gradle command so that should be fine.

**Comment by ThomasGorisse** [comment] 2021-06-18 18:02
I think it's better to wait for the SFB remove since there could have quite a lot of rules to clean just after trying to find them on a previous commit.

**Closed by ThomasGorisse** 2021-06-18 18:02 UTC
