### ISSUE TITLE
Can we play video on AR Surface ?

### ISSUE THREAD

**Issue by suryanadiminti99** [ThomasGorisse/sceneform-android-sdk#19] opened 2021-03-19 10:40 UTC
Hi Team, 
We can play video using Chromakey on scene form 1.51. But how can we play video in latest version of scene form . I tried like below.  I created cube and added texture to cube . But i am getting error . 

Texture.builder()
                .setSource(getApplicationContext(), Uri.fromFile(new File(videoUrl)))
                .build()
                .thenAccept(texture1 -> {
                    MaterialFactory.makeTransparentWithTexture(ArActivity.this, texture1)
                            .thenAccept(material -> {
                                material.setFloat("materialParams.alphaFactor", 1.0f);

                                //material.setTexture(PlaneRenderer.MATERIAL_TEXTURE, texture1);

                                ModelRenderable renderable = ShapeFactory.makeCube(new Vector3(new Vector3(Float.parseFloat(scalex), 0.0001f, Float.parseFloat(scaley))), Vector3.zero(), material);

                                AnchorNode anchorNode = new AnchorNode(anchor);

                                // Create a node to render the video and add it to the anchor.
                                Node videoNode = new Node();
                                anchorNode.setParent(arFragment.getArSceneView().getScene());
                                videoNode.setParent(anchorNode);

                               // Vector3 vectorScale = new Vector3(Float.parseFloat(scalex), 0.0001f, Float.parseFloat(scaley));

                                Vector3 vectorPos = new Vector3(Float.parseFloat(posx), Float.parseFloat(posy),(Float.parseFloat(posz)));

                                Quaternion rx = Quaternion.eulerAngles(new Vector3(Float.parseFloat(rotatex), 0.0f, 0.0f));
                                Quaternion ry = Quaternion.eulerAngles(new Vector3(0.0f, Float.parseFloat(rotatey), Float.parseFloat(rotatez)));

                                // Set Scaling
                              //  videoNode.setLocalScale(vectorScale);
                                // Set Position
                                videoNode.setLocalPosition(vectorPos);
                                // Set Rotation
                                videoNode.setLocalRotation(Quaternion.multiply(rx,ry));

                                // Start playing the video when the first node is placed.
                                if (!mediaPlayer.isPlaying()) {
                                    mediaPlayer.start();

                                    texture.getSurfaceTexture().setOnFrameAvailableListener(new SurfaceTexture.OnFrameAvailableListener() {
                                        @Override
                                        public void onFrameAvailable(SurfaceTexture surfaceTexture) {
                                            videoNode.setRenderable(renderable);
                                            texture.getSurfaceTexture().setOnFrameAvailableListener(null);
                                        }
                                    });

                                } else {
                                    videoNode.setRenderable(renderable);
                                }

                                // Stop Plane Renderable if data is loaded
                                if (planeRenderer!=null){
                                    planeRenderer.setEnabled(false);
                                }

                            });
                });

**Comment by ThomasGorisse** [comment] 2021-03-19 22:04
Duplicate of #21

**Comment by ThomasGorisse** [comment] 2021-03-23 21:26
Fixed here: 5c2f6ce24e2cc88490f065e53cf78eada8f0cc7a

**Closed by ThomasGorisse** 2021-03-23 21:26 UTC
Labels: duplicate
