### ISSUE TITLE
Camera Lag for Augmented Images on Samsung Galaxy S10

### ISSUE THREAD

**Issue by AleksaDjordjevic97** [ThomasGorisse/sceneform-android-sdk#149] opened 2021-08-28 17:00 UTC
There is a camera lag in the sample app for Augmented Images on Samsung Galaxy S10, Android 11. The lag is gone once it detects an image. Here is a video:

https://user-images.githubusercontent.com/62656452/131225324-ce0c5f73-e066-4299-b0da-8cb92699fbca.mp4

**Comment by AleksaDjordjevic97** [comment] 2021-08-28 17:20
One more issue that I am having is in my app. I copied the entire Activity from your Sample App for Augmented Images and when I try to open the activity in my app it crashes, and i click on WAIT, and after that it works great. Here is a video:

https://user-images.githubusercontent.com/62656452/131225724-841fa7cc-06a3-4cbf-9f7b-d74c6ec4d576.mp4

Also this is from the previous version, 1.19.5 and filament 1.10.6, and there is no camera lag there from the comment above

**Comment by ThomasGorisse** [comment] 2021-08-28 19:08
I don't completely understand your question.
Does this issue occurred in both 1.19.5 and 1.19.6?

It looks like something consuming is running from the MainThread.

Can you provide some code?

**Comment by AleksaDjordjevic97** [comment] 2021-08-29 13:12
The camera lag from the first comment is happening also in the sample app from this repository, not just in my app. It doesn't happen on the sample app in 1.19.5, but it does on the 1.19.6. But it happens only for the Augmented images sample, not others. I only have the Galaxy S10 for testing, but it doesn't lag on the Android Studio Emulator.

**Comment by RGregat** [comment] 2021-08-29 13:22
I can confirm the laggy behaviour on my Samsung Galaxy S20+ . My Pixel 4 has no issues.

**Comment by RGregat** [comment] 2021-08-29 13:48
The laggy behaviour is a result of a change in the `ExternalTexture` class. In 1.19.5 this part is marked as deprecated

```java
Stream.Builder()
                        .stream(textureId)
```

So i replaced it with the recommendet way. Maybe I did something wrong here. It's a little bit strange that the Pixel Smartphones are totally fine with the new way.

**Comment by RGregat** [comment] 2021-08-29 14:11
@AleksaDjordjevic97 pls check if the issue is gone with this hotfix https://github.com/ThomasGorisse/sceneform-android-sdk/tree/hotfix/green_frame_flickering

**Comment by AleksaDjordjevic97** [comment] 2021-08-29 14:19
Yes, no more camera lag. It works!

**Closed** 2021-08-31 15:57 UTC
